// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Ce fichier ne sert QUE la CLI Prisma (migrations, studio). On y met donc
    // la connexion directe : le pooler Supabase ne supporte pas les commandes
    // DDL en transaction. L'application, elle, se connecte via le pooler
    // (DATABASE_URL) au travers du driver adapter, voir src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
